### ISSUE TITLE
TransportError: Retry connection over the limit`

### ISSUE THREAD

**Issue by arthur-x88** [ScaledFoundations/GRID-playground#6]
`Traceback (most recent call last):
  File "/GRID/grid_chat.py", line 6, in <module>
    run_chat(config_path)
  File "build/bdist.linux-x86_64/egg/grid/chat.py", line 113, in run_chat
  File "build/bdist.linux-x86_64/egg/grid/orchestrator.py", line 171, in __enter__
AssertionError: Error in the initialization code block: An error occurred while executing the code:
Traceback (most recent call last)
Cell In[3], line 4
      2 from grid.model.model import ModelCollection
      3 import math, numpy
----> 4 airgendrone = AirGenDrone()
      5 modelcollection=ModelCollection(["seg-gsam","vqa-git","nav-inspect","detection-gdino"])
File build/bdist.linux-x86_64/egg/grid/robot/airgen_drone.py:46, in __init__(self, visual_assistant)
File /opt/conda/lib/python3.11/site-packages/airgen/client.py:2696, in connect_airgen(robot_type, ip_address, port, geo, run_in_background)
   2694 else:
   2695     client = robot_client_class(ip=host, port=port)
-> 2696 client.confirmConnection()
   2697 ## temp fix that the first segmentation image is not properly rendered
   2698 client.simGetImages(
   2699     [ImageRequest("front_center", ImageType.Segmentation, False, False)]
   2700 )
File /opt/conda/lib/python3.11/site-packages/airgen/client.py:165, in VehicleClient.confirmConnection(self)
    163 info: List[str] = []
    164 err_msg: List[str] = []
--> 165 if self.ping():
    166     info.append("Connected!")
    167 else:
File /opt/conda/lib/python3.11/site-packages/airgen/client.py:59, in VehicleClient.ping(self)
     52 def ping(self):
     53     """
     54     If connection is established then this call will return true otherwise it will be blocked until timeout
     55
     56     Returns:
     57         bool:
     58     """
---> 59     return self.client.call("ping")
File /opt/conda/lib/python3.11/site-packages/airgen_third_party/msgpackrpc/session.py:42, in Session.call(self, method, *args)
     41 def call(self, method, *args):
---> 42     return self.send_request(method, args).get()
File /opt/conda/lib/python3.11/site-packages/airgen_third_party/msgpackrpc/future.py:55, in Future.get(self)
     53 else:
     54     if isinstance(self._error, error.RPCError):
---> 55         raise self._error
     56     else:
     57         raise error.RPCError(self._error)
TransportError: Retry connection over the limit`

**Comment by saihv** [comment]
Please make sure the AirGen simulator is running. Also, could you let us know which platform you were running on? (Windows WSL or Linux)?

**Comment by fantasy4everts** [comment]
On Ubuntu, when I docker run  and  on the folder /GRID,   I add openai api key in  .env and modified a variable OPENAI_API_KEY.  I used gpt-3.5-turbo api,   Then I run python chat2grid.py.    After seconds,  there is prompt with  "GRID>     "   .  I am confusing,  I think the initial prompt should be "USER>    "  according to you example in GRID-playground.

**Comment by fantasy4everts** [comment]
BTW,  when I  enter something after prompt GRID>  ,  for example, what do you see?  .  It shows "Thinking"  all the time. stuck in the status.

**Comment by RalphX1** [comment]
Got something similar ut ond Windows WSL: "File /opt/conda/lib/python3.11/site-packages/airgen_third_party/msgpackrpc/session.py:42, in Session.call(self, method, *args)
     41 def call(self, method, *args):
---> 42     return self.send_request(method, args).get()
File /opt/conda/lib/python3.11/site-packages/airgen_third_party/msgpackrpc/future.py:55, in Future.get(self)
     53 else:
     54     if isinstance(self._error, error.RPCError):
---> 55         raise self._error
     56     else:
     57         raise error.RPCError(self._error)
TransportError: Retry connection over the limit"

**Comment by saihv** [comment]
@RalphX1 That error means the script is having trouble connecting to the AirGen simulator. Is the simulator running on the Windows side?

**Comment by RalphX1** [comment]
Yes, I have the simulator running.

**Comment by saihv** [comment]
Please find the new version of GRID at grid.scaledfoundations.ai - now fully web-based and includes all the old environments and robot capabilities, now enhanced with a full IDE for development.
